name: Portarias CI
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do repositorio
            uses: actions/checkout@1
            - name: Deploy para o servidor
            uses: easingthemes/ssh-deploy@main


