name: Portarias CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      - name: Ssh
        run: |
          mkdir -p ~/.ssh/
          echo "{{secrets.PRIVATE_KEY}}" > ../private.key
          sudo chmod 600 ../private.key
          ssh-keyscan -t rsa {{secrets.REMOTE_HOST}} > ~/.ssh/known_hosts
      - name: Git Pull
        run: |
          ssh {{secrets.REMOTE_USER}}@{{secrets.REMOTE_HOST}} \
          'cd {{secrets.REMOTE_TARGET}} && git pull'

